---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-apikey-secret
  namespace: traefik
type: Opaque
stringData:
  email: mzeinfahrozi@gmail.com
  apiKey: 0dd31277a97276fce313fd4e1c0e9d1d41c8b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |
    http:
      middlewares:
        headers-default:
          headers:
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN
            customRequestHeaders:
              X-Forwarded-Proto: https
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-json-certs
  namespace: traefik
spec:
  accessModes:
    - ReadWriteMany # I needed both for rw
    - ReadWriteOnce # I needed both for rw
  resources:
    requests:
      storage: 128Mi
