apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: who.zeinfahrozi.club
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-2
  template:
    metadata:
      labels:
        app: whoami-2
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-2
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: whoami-2
